# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RailsKit < Formula
  desc "Fast CLI toolkit for exploring Rails codebases — schema, routes, models, fixtures, locales"
  homepage "https://github.com/janstol/rails-kit"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/janstol/rails-kit/releases/download/v0.1.0/rails-kit_darwin_amd64.tar.gz"
      sha256 "37d1551439874dc548ef3734745322c2c1dcfa1ca1d64c6f3b0276b7e6241bbf"

      define_method(:install) do
        bin.install "rails-kit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/janstol/rails-kit/releases/download/v0.1.0/rails-kit_darwin_arm64.tar.gz"
      sha256 "8e74010936ea7c07d3143e66d845f0a1787e78cf226df020bb90c8f88bfe4726"

      define_method(:install) do
        bin.install "rails-kit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/janstol/rails-kit/releases/download/v0.1.0/rails-kit_linux_amd64.tar.gz"
      sha256 "04689c3b8541ed425df13b36ca8bada9c24e987214d344f17cd9f0a49472a0d3"
      define_method(:install) do
        bin.install "rails-kit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/janstol/rails-kit/releases/download/v0.1.0/rails-kit_linux_arm64.tar.gz"
      sha256 "fed360599696a3c18ef9846a94dcfb1dd1e8cd570f0e185e4d80cc5e5e1323d9"
      define_method(:install) do
        bin.install "rails-kit"
      end
    end
  end

  test do
    system "#{bin}/rails-kit", "version"
  end
end
