# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RailsKit < Formula
  desc "CLI toolkit for exploring Rails codebases without loading Rails"
  homepage "https://github.com/janstol/rails-kit"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/janstol/rails-kit/releases/download/v0.1.0/rails-kit_darwin_amd64.tar.gz"
      sha256 "eaf0495a716302219ca22007bdff73896b3c1954dd9583d4f6ec7b700ece800c"

      define_method(:install) do
        bin.install "rails-kit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/janstol/rails-kit/releases/download/v0.1.0/rails-kit_darwin_arm64.tar.gz"
      sha256 "29321c467ec01d61d9ef94bd86415ab30073c74ecb34d776fe06370f413d8e94"

      define_method(:install) do
        bin.install "rails-kit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/janstol/rails-kit/releases/download/v0.1.0/rails-kit_linux_amd64.tar.gz"
      sha256 "90e2677123da6b5e55cbdf82080385250ddcce193d65ebe58b24c52323cb533d"
      define_method(:install) do
        bin.install "rails-kit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/janstol/rails-kit/releases/download/v0.1.0/rails-kit_linux_arm64.tar.gz"
      sha256 "58a496e9969d2bccfb6eb507e657472909ab48aa81a77f84c3789a9e8c487548"
      define_method(:install) do
        bin.install "rails-kit"
      end
    end
  end

  test do
    system "#{bin}/rails-kit", "version"
  end
end
