# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RailsKit < Formula
  desc "CLI toolkit for exploring Rails codebases without loading Rails"
  homepage "https://github.com/janstol/rails-kit"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/janstol/rails-kit/releases/download/v0.2.0/rails-kit_darwin_amd64.tar.gz"
      sha256 "8a05130ec0f5afdd5813f7ff30e974293952dc87231480b8d9ba588c14c01009"

      define_method(:install) do
        bin.install "rails-kit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/janstol/rails-kit/releases/download/v0.2.0/rails-kit_darwin_arm64.tar.gz"
      sha256 "5db5335c949d8445fe3d9cd0b0ffe3d190205aedd4c9ee593f3bd5e6fee69e44"

      define_method(:install) do
        bin.install "rails-kit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/janstol/rails-kit/releases/download/v0.2.0/rails-kit_linux_amd64.tar.gz"
      sha256 "c96d98fda92085c246895af897a3c82fc342b1406e4dd5250deb3c475db36064"
      define_method(:install) do
        bin.install "rails-kit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/janstol/rails-kit/releases/download/v0.2.0/rails-kit_linux_arm64.tar.gz"
      sha256 "b201a9977c6d05b4878fc0df21213010e8f98b87a62476a81dbd126701e6a0c4"
      define_method(:install) do
        bin.install "rails-kit"
      end
    end
  end

  test do
    system "#{bin}/rails-kit", "version"
  end
end
